# Generated by Django 4.1.1 on 2023-01-05 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='cpassword',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='password',
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='joiningDate',
            field=models.DateField(null=True),
        ),
    ]
