# Generated by Django 4.1.1 on 2023-01-12 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='date')),
                ('Day', models.IntegerField(verbose_name='day')),
                ('Month', models.IntegerField(verbose_name='month')),
                ('Year', models.IntegerField(verbose_name='year')),
                ('Access_time', models.TimeField(verbose_name='access-time')),
                ('Logout_time', models.TimeField(verbose_name='logout-time')),
                ('Modified_time', models.TimeField(verbose_name='modified-time')),
                ('Time_worked', models.IntegerField(verbose_name='time-worked')),
                ('Employee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_date', models.DateField(verbose_name='start-date')),
                ('End_date', models.DateField(verbose_name='end-date')),
                ('No_of_Days', models.IntegerField(verbose_name='no-of-days')),
                ('description', models.TextField(blank=True, verbose_name='reason')),
                ('Approved', models.TextField(max_length=20, verbose_name='approved')),
                ('Type', models.CharField(max_length=20, verbose_name='type')),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
