# Generated by Django 4.1.1 on 2023-01-13 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_alter_leave_approved_alter_leave_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Employee2',
            new_name='Employee_name',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='description',
        ),
        migrations.AddField(
            model_name='leave',
            name='Employee_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leave',
            name='Reason',
            field=models.TextField(blank=True, null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
