# Generated by Django 4.1.1 on 2023-01-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_employee2_record_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='Pending_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default=1, max_length=25),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Medical', 'Medical')], max_length=10),
        ),
    ]
