# Generated by Django 4.1.1 on 2023-01-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_leave_pending_status_alter_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Time_worked',
            field=models.IntegerField(null=True, verbose_name='time-worked'),
        ),
    ]
