# Generated by Django 4.1.1 on 2023-01-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_record_time_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='No_of_Days',
            field=models.IntegerField(blank=True, null=True, verbose_name='no-of-days'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Pending_Status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default=1, max_length=25, null=True),
        ),
    ]
